In [2]:

import pandas as pd

path = '/workspaces/Interest/Business Observations - Sheet8.csv'
bad_data = pd.read_csv(path)

In [3]:
bad_data.shape

(36, 22)

In [4]:
bad_data.iloc[0]
bad_data.columns
setA = ('Unnamed: 0', '05/03', '05/04', 'Unnamed: 3', '05/10', '05/10.1',
       '05/11', '05/16', '05/16.1', '06/18', '05/19', '05/23', '05/23.1',
       '05/24', '05/30', '05/31', '06/01', '06/06', '06/07', '6/14', '06/14',
       '06/20')
setB =('05/03', '05/04', '05/09', '05/09.1', '05/11', '05/15', '05/15.1',
       '06/18', '05/19', '05/22', '05/22.1', '05/24', '05/30', '05/31',
       '06/01', '06/06', '06/07', '06/14', '006/14', '06/20')
list=[]
for item in setB:
    if item not in setA:
        list.append(item)
print(list)

['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

In [5]:
bad_data = bad_data.reset_index(drop=True)
bad_data.iloc[0]
bad_data

,Unnamed: 0,05/03,05/04,Unnamed: 3,05/10,05/10.1,05/11,05/16,05/16.1,06/18,...,05/23.1,05/24,05/30,05/31,06/01,06/06,06/07,6/14,06/14,06/20
0,1,0.0,0.0,NaN,NaN,NaN,29.0,12.0,10.0,8.0,...,28.0,28.0,15.0,13.0,13,3.0,NaN,22.0,NaN,283
1,2,20.0,20.0,NaN,10.0,10.0,9.0,NaN,24.0,20.0,...,13.0,10.0,11.0,3.0,3,28.0,26.0,11.0,NaN,300
2,3,15.0,15.0,NaN,9.0,9.0,8.0,5.0,4.0,NaN,...,24.0,24.0,3.0,10.0,9,5.0,NaN,19.0,NaN,191
3,4,28.0,28.0,NaN,22.0,22.0,22.0,16.0,16.0,15.0,...,9.0,9.0,28.0,26.0,26,16.0,18.0,10.0,NaN,237
4,5,6.0,6.0,NaN,NaN,NaN,29.0,27.0,26.0,25.0,...,27.0,28.0,24.0,22.0,22,19.0,18.0,9.0,NaN,279
5,6,18.0,18.0,NaN,3.0,2.0,2.0,27.0,22.0,22.0,...,9.0,9.0,NaN,27.0,27,19.0,19.0,11.0,NaN,328
6,7,NaN,29.0,NaN,27.0,27.0,27.0,25.0,25.0,25.0,...,20.0,18.0,15.0,14.0,14,13.0,14.0,6.0,NaN,209
7,8,10.0,8.0,NaN,13.0,11.0,6.0,26.0,26.0,23.0,...,17.0,16.0,5.0,12.0,12,10.0,12.0,3.0,NaN,243
8,9,6.0,6.0,NaN,1.0,1.0,1.0,26.0,25.0,25.0,...,23.0,23.0,NaN,18.0,18,7.0,8.0,2.0,NaN,202
9,10,5.0,5.0,NaN,4.0,4.0,4.0,0.0,0.0,NaN,...,27.0,27.0,NaN,21.0,21,12.0,14.0,6.0,NaN,97
10,11,17.0,17.0,NaN,10.0,10.0,10.0,9.0,9.0,9.0,...,NaN,27.0,NaN,13.0,29,12.0,31.0,19.0,NaN,43
11,12,NaN,27.0,NaN,1.0,1.0,NaN,14.0,1.0,NaN,...,NaN,28.0,NaN,0.0,0,28.0,4.0,14.0,NaN,88 cartons
12,13,12.0,5.0,NaN,21.0,21.0,28.0,8.0,5.0,27.0,...,2.0,2.0,NaN,11.0,27,27.0,NaN,NaN,NaN,NaN
13,14,NaN,29.0,NaN,19.0,18.0,15.0,8.0,6.0,29.0,...,16.0,16.0,NaN,4.0,2,10.0,17.0,4.0,NaN,NaN
14,15,16.0,0.0,NaN,13.0,4.0,1.0,8.0,2.0,NaN,...,12.0,6.0,NaN,17.0,16,21.0,NaN,NaN,NaN,NaN
15,16,14.0,18.0,NaN,NaN,NaN,28.0,12.0,0.0,NaN,...,3.0,2.0,NaN,NaN,29,54.0,16.0,16.0,NaN,NaN
16,17,14.0,14.0,NaN,59.0,59.0,59.0,26.0,23.0,14.0,...,50.0,43.0,NaN,7.0,4,10.0,48.0,24.0,NaN,NaN
17,18,5.0,NaN,NaN,7.0,5.0,28.0,3.0,NaN,28.0,...,26.0,26.0,NaN,24.0,23,9.0,8.0,1.0,NaN,NaN
18,19,8.0,8.0,NaN,NaN,NaN,29.0,22.0,20.0,14.0,...,8.0,8.0,NaN,17.0,15,10.0,13.0,2.0,NaN,NaN
19,20,7.0,6.0,NaN,0.0,0.0,0.0,55.0,50.0,50.0,...,45.0,44.0,NaN,6.0,4,47.0,5.0,28.0,NaN,NaN
20,21,27.0,22.0,NaN,NaN,NaN,59.0,36.0,22.0,17.0,...,44.0,42.0,NaN,15.0,12,28.0,39.0,11.0,NaN,NaN
21,22,40.0,39.0,NaN,11.0,8.0,5.0,6.0,NaN,23.0,...,4.0,NaN,NaN,30.0,29,17.0,28.0,38.0,NaN,NaN
22,23,16.0,16.0,NaN,46.0,46.0,31.0,49.0,43.0,32.0,...,1.0,NaN,NaN,35.0,34,55.0,7.0,6.0,NaN,NaN
23,24,NaN,NaN,NaN,47.0,47.0,46.0,32.0,27.0,27.0,...,17.0,15.0,NaN,57.0,56,36.0,50.0,43.0,NaN,NaN
24,25,NaN,NaN,NaN,NaN,NaN,48.0,0.0,47.0,45.0,...,57.0,57.0,NaN,40.0,33,0.0,6.0,37.0,NaN,NaN
25,26,17.0,31.0,NaN,7.0,1.0,1.0,40.0,39.0,37.0,...,22.0,21.0,NaN,2.0,2,7.0,55.0,47.0,NaN,NaN
26,27,27.0,15.0,NaN,NaN,NaN,57.0,45.0,39.0,31.0,...,11.0,9.0,NaN,24.0,22,14.0,59.0,39.0,NaN,NaN
27,28,31.0,31.0,NaN,27.0,27.0,27.0,24.0,23.0,23.0,...,20.0,20.0,NaN,16.0,16,84.0,11.0,62.0,NaN,NaN
28,29,NaN,56.0,NaN,41.0,41.0,40.0,20.0,16.0,13.0,...,59.0,57.0,NaN,90.0,90,63.0,NaN,8.0,NaN,NaN
29,30,46.0,46.0,NaN,32.0,32.0,32.0,22.0,18.0,18.0,...,NaN,97.0,NaN,75.0,75,69.0,NaN,50.0,NaN,NaN
30,31,42.0,34.0,NaN,1.0,1.0,148.0,45.0,45.0,44.0,...,120.0,118.0,NaN,101.0,101,116.0,NaN,31.0,NaN,NaN
31,32,80.0,80.0,NaN,72.0,71.0,148.0,70.0,68.0,67.0,...,19.0,19.0,NaN,130.0,129,99.0,NaN,68.0,NaN,NaN
32,33,NaN,NaN,NaN,121.0,117.0,116.0,34.0,33.0,33.0,...,142.0,138.0,NaN,122.0,122,104.0,NaN,76.0,NaN,NaN
33,34,82.0,82.0,NaN,64.0,64.0,63.0,33.0,33.0,33.0,...,133.0,125.0,NaN,110.0,110,107.0,NaN,78.0,NaN,NaN
34,35,3.0,75.0,NaN,58.0,58.0,48.0,133.0,178.0,128.0,...,146.0,146.0,NaN,110.0,107,280.0,NaN,55.0,NaN,NaN
35,36,69.0,66.0,NaN,24.0,21.0,20.0,NaN,273.0,264.0,...,114.0,116.0,NaN,72.0,71,NaN,NaN,169.0,NaN,NaN

In [6]:
bad_data.index
bad_data.head()
bad_data.iloc[0]
bad_data.iloc[[0]]
bad_data.columns

Index(['Unnamed: 0', '05/03', '05/04', 'Unnamed: 3', '05/10', '05/10.1',
       '05/11', '05/16', '05/16.1', '06/18', '05/19', '05/23', '05/23.1',
       '05/24', '05/30', '05/31', '06/01', '06/06', '06/07', '6/14', '06/14',
       '06/20'],
      dtype='str')

In [7]:
play_data = bad_data.rename(columns={'Unnamed: 0': '05/02', 'Unnamed: 3': '05/08','05/10': '05/09', '05/10.1': '05/10', '05/16': '05/15', '05/16.1': '05/16', '05/23': '05/22', '05/23.1': '05/23', '6/14': '06/14'})

prev_play_data = ['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

print(play_data.columns)
print(prev_play_data)



# play_data = bad_data.loc[:, ~bad_data.columns.str.contains('Unnamed')]
# play_data.columns = (
#    play_data.columns
#    .str.replace(r'05/10', '05/09', regex=True)   # fix inline date problems.
#    .str.replace(r'05/10.1', '05/10', regex=True)   # fix inline date problems.    
#    .str.replace(r'05/16', '05/15', regex=True)   # fix inline date problems.
#    .str.replace(r'05/16.1', '05/16', regex=True)   # fix inline date problems.
#    .str.replace(r'05/23', '05/22', regex=True)   # fix inline date problems.
#    .str.replace(r'05/23.1', '05/23', regex=True)   # fix inline date problems.
#    .str.replace(r'6/14', '06/14', regex=True)   # fix inline date problems.
#)

Index(['05/02', '05/03', '05/04', '05/08', '05/09', '05/10', '05/11', '05/15',
       '05/16', '06/18', '05/19', '05/22', '05/23', '05/24', '05/30', '05/31',
       '06/01', '06/06', '06/07', '06/14', '06/14', '06/20'],
      dtype='str')
['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

In [8]:
df = pd.DataFrame(play_data)
play_data.shape
df.drop(columns=['05/08', '06/14'], inplace=True)
df.shape
df.dtypes

05/02      int64
05/03    float64
05/04    float64
05/09    float64
05/10    float64
05/11    float64
05/15    float64
05/16    float64
06/18    float64
05/19    float64
05/22    float64
05/23    float64
05/24    float64
05/30    float64
05/31    float64
06/01      int64
06/06    float64
06/07    float64
06/20        str
dtype: object

In [9]:
df = df.apply(pd.to_numeric, errors='coerce')
df.fillna(0.0, inplace=True)
df.dtypes

05/02      int64
05/03    float64
05/04    float64
05/09    float64
05/10    float64
05/11    float64
05/15    float64
05/16    float64
06/18    float64
05/19    float64
05/22    float64
05/23    float64
05/24    float64
05/30    float64
05/31    float64
06/01      int64
06/06    float64
06/07    float64
06/20    float64
dtype: object

In [10]:
df.columns

Index(['05/02', '05/03', '05/04', '05/09', '05/10', '05/11', '05/15', '05/16',
       '06/18', '05/19', '05/22', '05/23', '05/24', '05/30', '05/31', '06/01',
       '06/06', '06/07', '06/20'],
      dtype='str')

In [11]:
# So things I'd be interested in for this set would be the sum of the total ticket changes per day. 
# Second I'd be interested in whether the days with large ticket value changes were related to the high value tickets or low value tickets. 
# Finally I'd be interested to determine which days with high ticket quatntiy changes that were high value and not low value.
# Finally I'd be interested in looking for patterns in mid-value tickets and what relates to their sale ~ $10.00 ticket purchases.  -- What causes the sale of specifically. 
# Finally What high ticket value changes were related to the low value ticket changes.  How might I prevent these occurances from happening in the future (likley idiot students or time wasters.

In [12]:
df.loc['Total'] = df.sum()
df_Total = pd.DataFrame(df.iloc[-1]).copy()
df_Total = df_Total.T

In [13]:
listA = df.sum(axis=1)[1:-1].tolist()

df_Ticket_Total = pd.DataFrame(listA, index=df.index[1:-1], columns=['Total']).T
df_Ticket_Total

,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
Total,538.0,359.0,569.0,617.0,590.0,555.0,496.0,448.0,309.0,262.0,...,419.0,453.0,626.0,607.0,1216.0,1161.0,1281.0,1227.0,1770.0,1524.0

In [14]:
df.index[1:-1]

Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
      dtype='object')

In [15]:
# Next on the agenda is to convert a PDF into a file I can crunch numbers on so I can look at the voter data.

In [16]:
stacked = pd.concat([df_Ticket_Total.rename(columns={'Total': 'Ticket Sold'}), df_Total.rename(columns={'Total': 'Total Amount'})], axis=0, ignore_index=True)

In [17]:
print(stacked)

       1      2      3      4      5      6      7      8      9     10  ...  \
0  538.0  359.0  569.0  617.0  590.0  555.0  496.0  448.0  309.0  262.0  ...
1    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  ...

    05/19   05/22   05/23   05/24  05/30   05/31   06/01   06/06  06/07  \
0     NaN     NaN     NaN     NaN    NaN     NaN     NaN     NaN    NaN
1  1196.0  1320.0  1268.0  1374.0  101.0  1294.0  1323.0  1439.0  526.0

    06/20
0     NaN
1  2412.0

[2 rows x 54 columns]

In [18]:
row1 = df_Ticket_Total.rename(columns={'Total': 'Ticket Sold'}).iloc[[0]]
row2 = df_Total.rename(columns={'Total': 'Total Amount'}).iloc[[0]]

stacked = pd.concat([row1, row2], axis=0, ignore_index=True)
stacked

,1,2,3,4,5,6,7,8,9,10,...,05/19,05/22,05/23,05/24,05/30,05/31,06/01,06/06,06/07,06/20
0,538.0,359.0,569.0,617.0,590.0,555.0,496.0,448.0,309.0,262.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1196.0,1320.0,1268.0,1374.0,101.0,1294.0,1323.0,1439.0,526.0,2412.0

In [19]:
del stacked

In [20]:
row1 = df_Ticket_Total.rename(columns={'Total': 'Ticket Sold'}).iloc[[0]]
row1 = row1.reset_index()
row2 = df_Total.rename(columns={'Total': 'Total Amount'}).iloc[[0]]
row2 = row2.reset_index()


stacked = pd.concat([row1, row2], axis=0, ignore_index=True)

In [21]:
stacked

,index,1,2,3,4,5,6,7,8,9,...,05/19,05/22,05/23,05/24,05/30,05/31,06/01,06/06,06/07,06/20
0,Total,538.0,359.0,569.0,617.0,590.0,555.0,496.0,448.0,309.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1196.0,1320.0,1268.0,1374.0,101.0,1294.0,1323.0,1439.0,526.0,2412.0

In [22]:
shape1 = df_Ticket_Total.shape
shape2 = df_Total.shape
print(shape1 + shape2)
df_Ticket_Total.columns

(1, 35, 1, 19)

Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
      dtype='object')

In [23]:
# this code isn't used but would be cleaner.
target_cols = df_Ticket_Total.columns.union(['Ticket Sold'])
# reindexing Ticket_Total
dfA = df_Ticket_Total.reindex(columns=[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])
# reindexing Total
list_B = df_Total.iloc[0].tolist()
dfB = pd.DataFrame([list_B])
dfB = dfB.reindex(columns=[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

# Creating a single table.
stacked = pd.concat([dfA, dfB], axis=0, ignore_index=True)
# Creating a table. 
stacked

,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
0,538.0,359.0,569.0,617.0,590.0,555.0,496.0,448.0,309.0,262.0,...,419.0,453.0,626.0,607.0,1216.0,1161.0,1281.0,1227.0,1770.0,1524.0
1,681.0,852.0,770.0,738.0,1224.0,918.0,1198.0,1169.0,1196.0,1320.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
dfB

,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
0,681.0,852.0,770.0,738.0,1224.0,918.0,1198.0,1169.0,1196.0,1320.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN