In [ ]:

import pandas as pd

path = '/workspaces/Interest/Business Observations - Sheet8.csv'
bad_data = pd.read_csv(path)

In [ ]:
bad_data.shape

(36, 22)

In [ ]:
bad_data.iloc[0]
bad_data.columns
setA = ('Unnamed: 0', '05/03', '05/04', 'Unnamed: 3', '05/10', '05/10.1',
       '05/11', '05/16', '05/16.1', '06/18', '05/19', '05/23', '05/23.1',
       '05/24', '05/30', '05/31', '06/01', '06/06', '06/07', '6/14', '06/14',
       '06/20')
setB =('05/03', '05/04', '05/09', '05/09.1', '05/11', '05/15', '05/15.1',
       '06/18', '05/19', '05/22', '05/22.1', '05/24', '05/30', '05/31',
       '06/01', '06/06', '06/07', '06/14', '006/14', '06/20')
list=[]
for item in setB:
    if item not in setA:
        list.append(item)
print(list)

['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

In [ ]:
bad_data = bad_data.reset_index(drop=True)
bad_data.iloc[0]

Unnamed: 0       1
05/03          0.0
05/04          0.0
Unnamed: 3     NaN
05/10          NaN
05/10.1        NaN
05/11         29.0
05/16         12.0
05/16.1       10.0
06/18          8.0
05/19          6.0
05/23         28.0
05/23.1       28.0
05/24         28.0
05/30         15.0
05/31         13.0
06/01           13
06/06          3.0
06/07          NaN
6/14          22.0
06/14          NaN
06/20          283
Name: 0, dtype: object

In [ ]:
bad_data.index
bad_data.head()
bad_data.iloc[0]
bad_data.iloc[[0]]
bad_data.columns

Index(['Unnamed: 0', '05/03', '05/04', 'Unnamed: 3', '05/10', '05/10.1',
       '05/11', '05/16', '05/16.1', '06/18', '05/19', '05/23', '05/23.1',
       '05/24', '05/30', '05/31', '06/01', '06/06', '06/07', '6/14', '06/14',
       '06/20'],
      dtype='str')

In [ ]:
play_data = bad_data.rename(columns={'Unnamed: 0': '05/02', 'Unnamed: 3': '05/08','05/10': '05/09', '05/10.1': '05/10', '05/16': '05/15', '05/16.1': '05/16', '05/23': '05/22', '05/23.1': '05/23', '6/14': '06/14'})

prev_play_data = ['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

print(play_data.columns)
print(prev_play_data)



# play_data = bad_data.loc[:, ~bad_data.columns.str.contains('Unnamed')]
# play_data.columns = (
#    play_data.columns
#    .str.replace(r'05/10', '05/09', regex=True)   # fix inline date problems.
#    .str.replace(r'05/10.1', '05/10', regex=True)   # fix inline date problems.    
#    .str.replace(r'05/16', '05/15', regex=True)   # fix inline date problems.
#    .str.replace(r'05/16.1', '05/16', regex=True)   # fix inline date problems.
#    .str.replace(r'05/23', '05/22', regex=True)   # fix inline date problems.
#    .str.replace(r'05/23.1', '05/23', regex=True)   # fix inline date problems.
#    .str.replace(r'6/14', '06/14', regex=True)   # fix inline date problems.
#)

Index(['05/02', '05/03', '05/04', '05/08', '05/09', '05/10', '05/11', '05/15',
       '05/16', '06/18', '05/19', '05/22', '05/23', '05/24', '05/30', '05/31',
       '06/01', '06/06', '06/07', '06/14', '06/14', '06/20'],
      dtype='str')
['05/09', '05/09.1', '05/15', '05/15.1', '05/22', '05/22.1', '006/14']

In [ ]:
df = pd.DataFrame(play_data)
play_data.shape
df.drop(columns=['05/08', '06/14'], inplace=True)
df.shape
df.dtypes

05/02      int64
05/03    float64
05/04    float64
05/09    float64
05/10    float64
05/11    float64
05/15    float64
05/16    float64
06/18    float64
05/19    float64
05/22    float64
05/23    float64
05/24    float64
05/30    float64
05/31    float64
06/01      int64
06/06    float64
06/07    float64
06/20        str
dtype: object

In [ ]:
df = df.apply(pd.to_numeric, errors='coerce')
df.fillna(0.0, inplace=True)
df.dtypes

05/02    float64
05/03    float64
05/04    float64
05/09    float64
05/10    float64
05/11    float64
05/15    float64
05/16    float64
06/18    float64
05/19    float64
05/22    float64
05/23    float64
05/24    float64
05/30    float64
05/31    float64
06/01    float64
06/06    float64
06/07    float64
06/20    float64
dtype: object

In [ ]:
df

,05/02,05/03,05/04,05/09,05/10,05/11,05/15,05/16,06/18,05/19,05/22,05/23,05/24,05/30,05/31,06/01,06/06,06/07,06/20
0,1.0,0.0,0.0,0.0,0.0,29.0,12.0,10.0,8.0,6.0,28.0,28.0,28.0,15.0,13.0,13.0,3.0,0.0,283.0
1,2.0,20.0,20.0,10.0,10.0,9.0,0.0,24.0,20.0,12.0,17.0,13.0,10.0,11.0,3.0,3.0,28.0,26.0,300.0
2,3.0,15.0,15.0,9.0,9.0,8.0,5.0,4.0,0.0,0.0,25.0,24.0,24.0,3.0,10.0,9.0,5.0,0.0,191.0
3,4.0,28.0,28.0,22.0,22.0,22.0,16.0,16.0,15.0,15.0,12.0,9.0,9.0,28.0,26.0,26.0,16.0,18.0,237.0
4,5.0,6.0,6.0,0.0,0.0,29.0,27.0,26.0,25.0,25.0,29.0,27.0,28.0,24.0,22.0,22.0,19.0,18.0,279.0
5,6.0,18.0,18.0,3.0,2.0,2.0,27.0,22.0,22.0,19.0,13.0,9.0,9.0,0.0,27.0,27.0,19.0,19.0,328.0
6,7.0,0.0,29.0,27.0,27.0,27.0,25.0,25.0,25.0,23.0,23.0,20.0,18.0,15.0,14.0,14.0,13.0,14.0,209.0
7,8.0,10.0,8.0,13.0,11.0,6.0,26.0,26.0,23.0,19.0,19.0,17.0,16.0,5.0,12.0,12.0,10.0,12.0,243.0
8,9.0,6.0,6.0,1.0,1.0,1.0,26.0,25.0,25.0,25.0,24.0,23.0,23.0,0.0,18.0,18.0,7.0,8.0,202.0
9,10.0,5.0,5.0,4.0,4.0,4.0,0.0,0.0,0.0,29.0,29.0,27.0,27.0,0.0,21.0,21.0,12.0,14.0,97.0
10,11.0,17.0,17.0,10.0,10.0,10.0,9.0,9.0,9.0,5.0,0.0,0.0,27.0,0.0,13.0,29.0,12.0,31.0,43.0
11,12.0,0.0,27.0,1.0,1.0,0.0,14.0,1.0,0.0,0.0,5.0,0.0,28.0,0.0,0.0,0.0,28.0,4.0,0.0
12,13.0,12.0,5.0,21.0,21.0,28.0,8.0,5.0,27.0,25.0,7.0,2.0,2.0,0.0,11.0,27.0,27.0,0.0,0.0
13,14.0,0.0,29.0,19.0,18.0,15.0,8.0,6.0,29.0,0.0,18.0,16.0,16.0,0.0,4.0,2.0,10.0,17.0,0.0
14,15.0,16.0,0.0,13.0,4.0,1.0,8.0,2.0,0.0,29.0,21.0,12.0,6.0,0.0,17.0,16.0,21.0,0.0,0.0
15,16.0,14.0,18.0,0.0,0.0,28.0,12.0,0.0,0.0,29.0,10.0,3.0,2.0,0.0,0.0,29.0,54.0,16.0,0.0
16,17.0,14.0,14.0,59.0,59.0,59.0,26.0,23.0,14.0,10.0,56.0,50.0,43.0,0.0,7.0,4.0,10.0,48.0,0.0
17,18.0,5.0,0.0,7.0,5.0,28.0,3.0,0.0,28.0,21.0,27.0,26.0,26.0,0.0,24.0,23.0,9.0,8.0,0.0
18,19.0,8.0,8.0,0.0,0.0,29.0,22.0,20.0,14.0,14.0,8.0,8.0,8.0,0.0,17.0,15.0,10.0,13.0,0.0
19,20.0,7.0,6.0,0.0,0.0,0.0,55.0,50.0,50.0,50.0,45.0,45.0,44.0,0.0,6.0,4.0,47.0,5.0,0.0
20,21.0,27.0,22.0,0.0,0.0,59.0,36.0,22.0,17.0,17.0,50.0,44.0,42.0,0.0,15.0,12.0,28.0,39.0,0.0
21,22.0,40.0,39.0,11.0,8.0,5.0,6.0,0.0,23.0,22.0,8.0,4.0,0.0,0.0,30.0,29.0,17.0,28.0,0.0
22,23.0,16.0,16.0,46.0,46.0,31.0,49.0,43.0,32.0,27.0,5.0,1.0,0.0,0.0,35.0,34.0,55.0,7.0,0.0
23,24.0,0.0,0.0,47.0,47.0,46.0,32.0,27.0,27.0,20.0,19.0,17.0,15.0,0.0,57.0,56.0,36.0,50.0,0.0
24,25.0,0.0,0.0,0.0,0.0,48.0,0.0,47.0,45.0,37.0,58.0,57.0,57.0,0.0,40.0,33.0,0.0,6.0,0.0
25,26.0,17.0,31.0,7.0,1.0,1.0,40.0,39.0,37.0,36.0,26.0,22.0,21.0,0.0,2.0,2.0,7.0,55.0,0.0
26,27.0,27.0,15.0,0.0,0.0,57.0,45.0,39.0,31.0,27.0,12.0,11.0,9.0,0.0,24.0,22.0,14.0,59.0,0.0
27,28.0,31.0,31.0,27.0,27.0,27.0,24.0,23.0,23.0,23.0,22.0,20.0,20.0,0.0,16.0,16.0,84.0,11.0,0.0
28,29.0,0.0,56.0,41.0,41.0,40.0,20.0,16.0,13.0,11.0,0.0,59.0,57.0,0.0,90.0,90.0,63.0,0.0,0.0
29,30.0,46.0,46.0,32.0,32.0,32.0,22.0,18.0,18.0,15.0,0.0,0.0,97.0,0.0,75.0,75.0,69.0,0.0,0.0
30,31.0,42.0,34.0,1.0,1.0,148.0,45.0,45.0,44.0,149.0,120.0,120.0,118.0,0.0,101.0,101.0,116.0,0.0,0.0
31,32.0,80.0,80.0,72.0,71.0,148.0,70.0,68.0,67.0,57.0,20.0,19.0,19.0,0.0,130.0,129.0,99.0,0.0,0.0
32,33.0,0.0,0.0,121.0,117.0,116.0,34.0,33.0,33.0,23.0,143.0,142.0,138.0,0.0,122.0,122.0,104.0,0.0,0.0
33,34.0,82.0,82.0,64.0,64.0,63.0,33.0,33.0,33.0,21.0,133.0,133.0,125.0,0.0,110.0,110.0,107.0,0.0,0.0
34,35.0,3.0,75.0,58.0,58.0,48.0,133.0,178.0,128.0,117.0,148.0,146.0,146.0,0.0,110.0,107.0,280.0,0.0,0.0
35,36.0,69.0,66.0,24.0,21.0,20.0,0.0,273.0,264.0,238.0,140.0,114.0,116.0,0.0,72.0,71.0,0.0,0.0,0.0

In [ ]:
# So things I'd be interested in for this set would be the sum of the total ticket changes per day. 
# Second I'd be interested in whether the days with large ticket value changes were related to the high value tickets or low value tickets. 
# Finally I'd be interested to determine which days with high ticket quatntiy changes that were high value and not low value.
# Finally I'd be interested in looking for patterns in mid-value tickets and what relates to their sale ~ $10.00 ticket purchases.  -- What causes the sale of specifically. 
# Finally What high ticket value changes were related to the low value ticket changes.  How might I prevent these occurances from happening in the future (likley idiot students or time wasters.

In [ ]:
df.loc['Total'] = df.sum()
df_Total = pd.DataFrame(df.iloc[-1]).copy()
df_Total.T

,05/02,05/03,05/04,05/09,05/10,05/11,05/15,05/16,06/18,05/19,05/22,05/23,05/24,05/30,05/31,06/01,06/06,06/07,06/20
Total,666.0,681.0,852.0,770.0,738.0,1224.0,918.0,1198.0,1169.0,1196.0,1320.0,1268.0,1374.0,101.0,1294.0,1323.0,1439.0,526.0,2412.0

In [ ]:
listA = df.sum(axis=1)[1:-1].tolist()

pd.DataFrame(listA, index=df.index[1:-1], columns=['Total']).T

ValueError: Shape of passed values is (37, 1), indices imply (35, 1)

In [ ]:
df.index[1:-1]

Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
      dtype='object')

In [ ]:
# Next on the agenda is to convert a PDF into a file I can crunch numbers on so I can look at the voter data.