##### Journal Working with 2026_primary_candidate_list_by_contest_federal_and_state.pdf

##### First I Need to Pick My Conversion Method
* pyplumber
> Great way to work with paragraph entries, not good at working with data or tables. 
* tabula 
> Perfect data integrity.
> The file is converted directly into the DataFrame. 
* camelot
> I think this one was the quickest to use so I'm going to start with that one. 
* pdf2image 
> I didn't get to mess with this one.

In [8]:
# Beginning work with the camelot function 

import camelot

tables = camelot.read_pdf("/workspaces/Interest/2026_primary_candidate_list_by_contest_federal_and_state.pdf", pages="1", flavor="stream")
tables[0].df

,0,1,2,3,4,5
0,,,"CRITERIA: Election: 03/03/2026, Show Contest ...",,,
1,CANDIDATE NAME,NAME ON BALLOT,PARTY,FILING DATE,ADDRESS,
2,US SENATE (DEM),,,,,
3,"FARROW, DARYL TRENT",Daryl Farrow,DEM,12/05/2025,5114 WESTERN BLVD 1206,"JACKSONVILLE, NC 28546"
4,"DUES, JUSTIN EDWARD",Justin E. Dues,DEM,12/18/2025,2423 BAXTER PL SE,"CONCORD, NC 28025"
5,"COOPER, ROY ASBERRY III",Roy Cooper,DEM,12/03/2025,PO BOX 1190,"RALEIGH, NC 27602"
6,"COLON, ROBERT JOHN",Robert Colon,DEM,12/18/2025,165 RAYMOND WILLIAMS RD,"ROCKY POINT, NC 28457"
7,"WILLIAMS, MARCUS WHITTMAN",Marcus W. Williams,DEM,12/12/2025,P O BOX 7806,"WILMINGTON, NC 28406"
8,"QUICK, ORRICK ROMAINE",Orrick Quick,DEM,12/17/2025,1442 CEDROW DR,"HIGH POINT, NC 27260"
9,US SENATE (REP),,,,,
10,"DUPRE, MARGOT PATRICE",Margot Dupre,REP,12/11/2025,601 S KINGS DR F,"CHARLOTTE, NC 28204"
11,"DANSIE, RICHARD TRACY",Richard Dansie,REP,12/19/2025,1821 HILLINDALE RD,"DURHAM, NC 27705"
12,,,,,SUITE 1B-199,
13,"BROWN, DONALD MITCHELL JR",Donald M. (Don) Brown,REP,12/01/2025,10440 PARK ROAD,"WAXHAW, NC 28210"
14,,,,,SUITE 200,
15,"WHATLEY, MICHAEL DAVID",Michael Whatley,REP,12/02/2025,1812 KENDRICK RD,"GASTONIA, NC 28056"
16,"TEMPLE, ELIZABETH ANNE",Elizabeth A. Temple,REP,12/01/2025,904 CHESTNUT DR,"SMITHFIELD, NC 27577"
17,"MORROW, MICHELE MARIE",Michele Morrow,REP,12/18/2025,423 OAKRIDGE RD,"CARY, NC 27511"
18,"JOHNSON, THOMAS LEE",Thomas Johnson,REP,12/15/2025,1220 TIMBER DRIVE EAST,"GARNER, NC 27529"
19,,,,,SUITE 1099,
20,US HOUSE OF REPRESENTATIVES DISTRICT 01 (REP),,,,,
21,"BUCKHOUT, LAURIE GAYE MOE",Laurie Buckhout,REP,12/19/2025,210 BLAIR CT,"EDENTON, NC 27932"
22,"BUCK, ASA BRYANT III",Asa Buck,REP,12/05/2025,1903 LIVE OAK STREET NUMBER 3,"BEAUFORT, NC 28516"
23,"RUSSELL, ASHLEY-NICOLE PRESSLY",Ashley-Nicole Russell,REP,12/09/2025,239 SEA DREAMS DR,"ATLANTIC BEACH, NC 28512"
24,"ROUSE, ERIC SEAN",Eric Rouse,REP,12/02/2025,2856 ALTON PHILLIPS RD,"KINSTON, NC 28504"
25,"HANIG, ROBERT OTHO",Bobby Hanig,REP,12/01/2025,102 ORCHARD LN,"POWELLS POINT, NC 27966"

##### Notes from the camelot method. 

* When I first attempted to run the file I got a IndexError: "list index out of range" error message.  
* I suppressed the output by adding the *"pages" & *"flavor" specifiers. --> Now I see that the I receive 25 rows of output.
* I have attempted to modify the "pages" field to get more of the data out of the table, but results are limited to 25. 

> && It has really seemed too easy to do this. 

##### Looking at the actual data 

- The first line is the CRITERIA: Eelection 03/03/2026, Show Contest w/o Condidate: Y, County: ALL COUNTIES, Data Source: STATE ONLY VIEW

- 1 LINE 1: includes the headers 
{CANDIDATE NAME, NAME ON BALLET, PARTY, FILING DATE, ADDRESS}
- 2 LINE 2: US SENATE (DEM)
- 3 LINE 3-8: Contains Specific Voter Information.
- 4 LINE 9: US SENATE (REP)
> *"I left off here"*
- 5 **LINE 12: It appears that the a couple of the entries are having their address split up.  '/n' character not seen [ENTER] caused a new row and contents for the room specifier were added to a new line.**

In [9]:
tables = camelot.read_pdf("/workspaces/Interest/2026_primary_candidate_list_by_contest_federal_and_state.pdf", pages="1-5", flavor="stream")
tables[4].df

,0,1,2,3,4,5
0,STATE BOARD OF ELECTIONS,,,,,CANDIDATE LIST GROUPED BY CONTEST
1,CANDIDATE NAME,NAME ON BALLOT,PARTY,FILING DATE,ADDRESS,
2,US HOUSE OF REPRESENTATIVES DISTRICT 11 (DEM),,,,,
3,"BRIARWOOD, ZELDA THAKER",Zelda Briarwood,DEM,12/17/2025,P.O. BOX 112,"CANTON, NC 28716"
4,"AGER, JAMES PETERSON",Jamie Ager,DEM,12/01/2025,331 EARLY BIRD LN,"FAIRVIEW, NC 28730"
5,"WHIPPLE, LEE",Lee Whipple,DEM,12/17/2025,12 MAIN ST,"ASHEVILLE, NC 28803"
6,"MADDOX, PAUL SAMUEL",Paul Maddox,DEM,12/04/2025,75 HAT CREEK TRL,"BURNSVILLE, NC 28714"
7,"HUDSPETH, RICHARD WILLIAM",Richard Hudspeth,DEM,12/09/2025,PO BOX 1101,"SKYLAND, NC 28776"
8,US HOUSE OF REPRESENTATIVES DISTRICT 11 (REP),,,,,
9,"EDWARDS, CHARLES MARION",Chuck Edwards,REP,12/01/2025,127 BERRY CREEK DR,"FLAT ROCK, NC 28731"
10,"SMITH, ADAM RION",Adam R. Smith,REP,12/03/2025,PO BOX 1159,"FAIRVIEW, NC 28730"
11,US HOUSE OF REPRESENTATIVES DISTRICT 12 (DEM),,,,,
12,"ADAMS, ALMA SHEALEY",Alma Shealey Adams,DEM,12/09/2025,PO BOX 31473,"CHARLOTTE, NC 28231"
13,"WILLIAMSON, MONACA MAYE",Monaca Maye Williamson,DEM,12/11/2025,6210 RUSSWOOD DR,"PLEASANT GARDEN, NC 27313"
14,US HOUSE OF REPRESENTATIVES DISTRICT 12 (REP),,,,,
15,"CODIGA, JOHN CHRISTOPHER",Jack Codiga,REP,12/16/2025,2820 SELWYN AVE STE 130-668,"CHARLOTTE, NC 28209"
16,"ALI, ADDUL RAHMAN EL",Addul Ali,REP,12/17/2025,6815 JAMISON LN,"CHARLOTTE, NC 28269"
17,US HOUSE OF REPRESENTATIVES DISTRICT 13 (DEM),,,,,
18,"BARRINGER, PAUL JEHU III",Paul Barringer,DEM,12/01/2025,PO BOX 114,"SANFORD, NC 27331"
19,"PIERCE, JEREMIAH-FRANK LEE",Frank Pierce,DEM,12/19/2025,PO BOX 1371,"RALEIGH, NC 27615"
20,"NICHOLI, ALEXANDER",Alexander Nicholi,DEM,12/04/2025,PO BOX 45,"RALEIGH, NC 27602"
21,US HOUSE OF REPRESENTATIVES DISTRICT 13 (REP),,,,,
22,"SHARMA, SIDDHANTH",Sid Sharma,REP,12/18/2025,P.O. BOX 937,"MORRISVILLE, NC 27560"
23,"KNOTT, JOHN BRADFORD",Brad Knott,REP,12/15/2025,3340 ALLEGHANY DR,"RALEIGH, NC 27609"